version: '3'

services:
  app:
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile

    volumes:
      - .:/app/
      - /app/node_modules
    container_name: house-services
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_VERSION: ${APP_VERSION}
      STAGE: ${STAGE}
      PORT: ${PORT}